language: android
android:
  components:
  - build-tools-20.0.0
  - android-20
  - sysimg-20
  - add-on
  - extra
  licenses:
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+
jdk: oraclejdk7

env:
  global:
  - ANDROID_SDK_VERSION="r23.0.2"
  matrix:
  - ANDROID_SDKS=android-20,sysimg-20  ANDROID_TARGET=android-20  ANDROID_ABI=armeabi-v7a

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  # for gradle output style
  - export TERM=dumb
  # newest Android NDK
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86.tar.bz2 -O ndk.tgz; fi
  - tar -xf ndk.tgz
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r9c
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}



notifications:
  email: true

script:
  ./gradlew clean build
